eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    preferIpAddress: false


server:
  port: 9999

spring:
  security:
    user:
      password: password

security.user.password: password

security.oauth2.client:
  clientId: client
  clientSecret: secret
  authorized-grant-types: authorization_code,refresh_token,implicit,password,client_credentials
  scope: webshop

logging.level:
  root: WARN
  org:
    springframework:
      security:
        oauth2: DEBUG
          config:
            annotation.web.configurers.FrameworkEndpointHandlerMapping: INFO
          provider:
            client.ClientCredentialsTokenGranter: DEBUG
            password.ResourceOwnerPasswordTokenGranter: DEBUG
            code.AuthorizationCodeTokenGranter: DEBUG
            implicit.ImplicitTokenGranter: DEBUG
            approval.ApprovalStoreUserApprovalHandler: DEBUG
            endpoint.TokenEndpoint: INFO
            approval.AuthorizationEndpoint: INFO

  # Set INFO to see the allocated port
      boot:
        context:
          embedded:
            tomcat.TomcatEmbeddedServletContainer: INFO
            undertow.UndertowEmbeddedServletContainer: INFO

  se.callista: INFO


---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/